### ISSUE TITLE
(attached and relatable) keys arranged at the end

### ISSUE THREAD

**Issue by mohamedsabil83** [andrey-helldar/laravel-lang-publisher#77]
- Lang Publisher Version: 8.2.0
- Laravel Version: 8.35.1
- PHP Version: 7.4.16

![Screenshot from 2021-04-01 17-23-28](https://user-images.githubusercontent.com/10126040/113309420-cdb64880-930f-11eb-869e-37f6e99950d1.png)

**Comment by andrey-helldar** [comment]
Fixed in version [v8.2.1](https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v8.2.1).

Thank you!

**Comment by mohamedsabil83** [comment]
I reviewed the update and needs a little fix:

![Screenshot from 2021-04-04 16-59-17](https://user-images.githubusercontent.com/10126040/113511367-208a3d00-9568-11eb-93bf-25569bb14a91.png)

**Comment by andrey-helldar** [comment]
Yes indeed. Didn't notice.
I will correct this mistake today or tomorrow.

![image](https://user-images.githubusercontent.com/10347617/113512579-f63b7e00-956d-11eb-81bf-65e5e7b81599.png)

**Comment by andrey-helldar** [comment]
PS: This is very strange. On the third attempt to invoke the command, the key was sorted correctly. I'll check.

![image](https://user-images.githubusercontent.com/10347617/113512652-431f5480-956e-11eb-82d0-08038a0851d6.png)

**Comment by andrey-helldar** [comment]
I figured out what the problem was - I called the sort method before combining the array:

![image](https://user-images.githubusercontent.com/10347617/113512767-c640aa80-956e-11eb-806d-db8e94a79d36.png)

Fixed:

![image](https://user-images.githubusercontent.com/10347617/113512929-bc6b7700-956f-11eb-8b8c-f0773fe142db.png)

Please update the package: `composer update`.

Version [v8.4.1](https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v8.4.1) released.
